// Next.js normally supplies this ambient declaration itself via
// `next-env.d.ts`'s `/// <reference types="next/image-types/global" />`
// line — but that file is gitignored and only ever regenerated by the
// Next.js CLI (`next dev`/`next build`/`next lint`), none of which run
// before `tsc --noEmit` in CI (`npm run lint` here is plain `eslint`,
// not `next lint`). A fresh checkout therefore has no `next-env.d.ts`
// at all when typecheck runs, and no ambient `*.png` module declaration
// with it — reproduced locally by removing the (gitignored) file and
// rerunning `npm run typecheck`. This file makes the declaration this
// project's own static image imports (`leaflet/dist/images/*.png` in
// `components/map/nearby-map.tsx`) need independent of that run-order
// assumption, committed so CI and local development resolve identically.
declare module "*.png" {
  import type { StaticImageData } from "next/image";
  const content: StaticImageData;
  export default content;
}
